export const baseUrl:string = "http://localhost:4200/api/"
export const addProject:string = "addProject"
export const getProject:string = "getProject/"
export const addKnowledge:string = "addKnowledge/"
export const getKnowledge:string = "getKnowledge/"
export const getProjectList:string = "getProjects"
export const getProjectById:string = "getProjectById/"
export const deleteProblem:string = "getDeleteProjectById/"
